### ISSUE TITLE
cl codegen, replace template ty args in function body

### ISSUE THREAD

**Issue by Olliewer** [descend-lang/descend-pjs-22-23#16]
e.g. 
```RUST
fn foo<T: ty>(y: T) -[cpu.thread]-> T {
  let x: T = y;
}
```
function call ``foo<i32>(param1);``
soll folgende Funktionsdefinition erzeugen:
```Cpp
descend::i32 foo_i32(descend::i32 x) {
    typedef T descend::i32
    T x = y;
    return y;
}
```
Der Name der Funktion wird bereits verändert

Anpassungen in `gen_global_fn_call()`

**Comment by jrhino97** [comment]
Der CPP Ast muss um eine Möglichkeit erweitert werden um typedefs abzubilden und dann muss ein Typedef als erstes STMT im Body der getemplateten Funktion hinzugefügt werden.

**Comment by jrhino97** [comment]
Ist im Main Branch umgesetzt. Allerdings wird kein Typedef erzeugt, sondern die Typen direkt ersetzt. Dafür wurde der Test test_template_type hinzugefügt
