### ISSUE TITLE
Generiere korrekte Funktionsaufrufe für Synchronisationen, korrektes indexing auf GPU

### ISSUE THREAD

**Issue by Olliewer** [descend-lang/descend-pjs-22-23#19]
zur Synchronisation wird ``syncthreads(); `` generiert
und das indexing auf Arrays im Kernel geschieht durch ``((blockIdx.x * bs) + threadIdx.x)``

**Comment by FloWag** [comment]
replaced syncthreads() with barrier(CLK_LOCAL_MEM_FENCE)

**Comment by jrhino97** [comment]
Die Lösung von Florian hab ich in den Main-Branch übernommen. Außerdem generieren wir jetzt get_local_id und get_group_id statt blockIdx und threadIdx
