### ISSUE TITLE
Eigenes Print Makro mit Error Handling

### ISSUE THREAD

**Issue by jrhino97** [descend-lang/descend-pjs-22-23#31]
Im Printer haben wir an vielen Stellen Konstrukte wie dieses: 
`let res = write!(&mut s, "__kernel ");
                    if res.is_err() {
                        panic!("{:?}", res);
                    }`

Die machen die Code schwerer zu lesen und könnten vermutlich durch ein eigenes Makro abgebildet werden. Wir sollten daher ein Makro schreiben, dass die Fehlerüberprüfung abbildet, sodass wir die write! Aufrufe in einem Einzeiler machen können.

**Comment by roneric** [comment]
der code ist auch unnötig kompliziert, wir müssen das nicht wie bei C machen :)
man kann einfach `let res = write!(&mut s, "__kernel ").unwrap();` schreiben, macht dasselbe.
