### ISSUE TITLE
Generate OpenCL ast

### ISSUE THREAD

**Issue by Olliewer** [descend-lang/descend-pjs-22-23#4]
- [x] generate OpenCL ast in new module.
- [ ] Specify grammar in EBNF
- [ ] Refactor cu_ast to cpp AST and use it in both modules
- [ ] Refactor Header so Kernel Loading is done by Kernel String

**Comment by jrhino97** [comment]
Ich glaube dieses Issue brauchen wir nun auch nicht mehr. Es gibt ja keinen CL-Ast. Vielleicht sollten wir noch einmal über den Pull-Request schauen um zu sehen ob wir da irgendwo changes haben die wir für main auch noch brauchen
